apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lifebank-storage
  labels:
    version: ${VERSION}
provisioner: driver.longhorn.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
reclaimPolicy: Retain
allowVolumeExpansion: true
